apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"rbac.authorization.k8s.io/v1\",\"kind\":\"ClusterRoleBinding\",\"metadata\":{\"annotations\":{},\"labels\":{\"app.kubernetes.io/name\":\"kube-state-metrics\",\"app.kubernetes.io/version\":\"2.1.0\"},\"name\":\"kube-state-metrics\"},\"roleRef\":{\"apiGroup\":\"rbac.authorization.k8s.io\",\"kind\":\"ClusterRole\",\"name\":\"kube-state-metrics\"},\"subjects\":[{\"kind\":\"ServiceAccount\",\"name\":\"kube-state-metrics\",\"namespace\":\"monitoring\"}]}\n"},"creationTimestamp":"2024-07-22T05:35:35Z","labels":{"app.kubernetes.io/name":"kube-state-metrics","app.kubernetes.io/version":"2.1.0"},"name":"kube-state-metrics","resourceVersion":"37900","uid":"515611bd-831f-41fc-87e0-a33086d1c111"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"kube-state-metrics"},"subjects":[{"kind":"ServiceAccount","name":"kube-state-metrics","namespace":"monitoring"}]}
  creationTimestamp: "2024-07-22T05:35:35Z"
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.1.0
  name: kube-state-metrics
  resourceVersion: "35277"
  uid: 9e077bf5-2c9f-4ca2-95a4-514056f347d4
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-state-metrics
subjects:
- kind: ServiceAccount
  name: kube-state-metrics
  namespace: monitoring
